#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — provisionamento do runner brasileiro do escalaHRO.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
TOTAL_MINUTES=35

REPO="joaohperes/escala-hro"
RUNNER_NAME="escala-vps-br"
RUNNER_LABEL="escala-br"

# remoto "comando" — roda um comando no VPS por SSH.
remoto() {
  local opts=(-o StrictHostKeyChecking=accept-new -o ConnectTimeout=15)
  [[ -n "${VPS_SSH_KEY:-}" ]] && opts+=(-i "$VPS_SSH_KEY")
  ssh "${opts[@]}" "${VPS_USER}@${VPS_HOST}" "$@"
}

banner "escalaHRO — runner próprio no Brasil"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Pré-requisitos" 2
say "Este wizard cria o runner que roda a extração diária da escala."
note "Motivo: desde 16/08/2026 o escala.med.br só entrega os arquivos do site"
note "para requisições vindas do Brasil. Os runners do GitHub ficam nos EUA."
printf '\n'
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  say "✓ gh CLI autenticado"
else
  warn "gh CLI não está autenticado. Rode 'gh auth login' em outro terminal e volte."
  pause "Feito? Enter para continuar"
fi
command -v ssh >/dev/null 2>&1 || warn "ssh não encontrado — instale antes de continuar"
pause "Enter para começar"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Criar a máquina virtual em região brasileira" 10
say "Crie uma VM Ubuntu 24.04 LTS x86_64 numa região do Brasil."
say "O IP precisa ser brasileiro — é isso que destrava o escala.med.br."
printf '\n'
say "Opções (escolha uma):"
step "Oracle Cloud — região São Paulo (br-sao-paulo-1). Tem free tier permanente."
step "AWS EC2 — região sa-east-1 (São Paulo). t3.small, ~US\$15/mês."
step "Magalu Cloud / Locaweb — provedores nacionais, cobrança em real."
printf '\n'
say "Requisitos da VM, qualquer que seja o provedor:"
note "  - Ubuntu 24.04 LTS, arquitetura x86_64 (não ARM: o Chrome oficial só tem x86_64)"
note "  - 2 GB de RAM ou mais (o Chrome headless é o que mais consome)"
note "  - 15 GB de disco"
note "  - porta 22 liberada para o seu IP; não precisa abrir mais nada"
note "  - sua chave SSH pública cadastrada no momento da criação"
printf '\n'
if confirm "Abrir o console da Oracle Cloud?"; then
  open_url "https://cloud.oracle.com/compute/instances"
fi
pause "Quando a VM estiver rodando e você tiver o IP público, Enter"

ask VPS_HOST "IP público da VM:"
ask VPS_USER "Usuário SSH (ubuntu na AWS/Magalu, opc ou ubuntu na Oracle):"
ask VPS_SSH_KEY "Caminho da chave SSH privada (Enter para usar o ssh-agent):"
write_env VPS_HOST "$VPS_HOST"
write_env VPS_USER "$VPS_USER"
write_env VPS_SSH_KEY "$VPS_SSH_KEY"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Testar a conexão SSH" 2
say "Conectando em ${VPS_USER}@${VPS_HOST} ..."
if remoto "echo conectado; lsb_release -ds; uname -m; nproc; free -m | awk '/Mem:/{print \$2\" MB de RAM\"}'"; then
  say "✓ SSH funcionando"
else
  warn "não consegui conectar. Confira IP, usuário, chave e o firewall da VM."
  exit 1
fi
pause "Enter para continuar"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Confirmar que a VM enxerga o escala.med.br" 3
say "Checagem decisiva: baixar do VPS o bundle JS do escala.med.br."
say "De fora do Brasil ele volta com poucos KB de HTML; do Brasil, ~1,5 MB de JS."
printf '\n'
if remoto 'bash -s' <<'REMOTO'
set -e
BUNDLE=$(curl -s https://escala.med.br/ | grep -o 'scripts/vendor\.[a-z0-9]*\.js' | head -1)
[ -n "$BUNDLE" ] || { echo "não consegui achar o nome do bundle no index"; exit 1; }
TAM=$(curl -s -o /dev/null -w '%{size_download}' "https://escala.med.br/$BUNDLE")
echo "IP de saída: $(curl -s https://ipinfo.io/country 2>/dev/null | tr -d '\n')"
echo "bundle: $BUNDLE  tamanho: $TAM bytes"
if [ "$TAM" -lt 100000 ]; then
  echo "BLOQUEADO: o CDN devolveu HTML no lugar do JS."
  exit 1
fi
echo "OK: o VPS recebe os arquivos reais."
REMOTO
then
  say "✓ A VM tem acesso liberado ao escala.med.br"
else
  warn "Esta VM está bloqueada igual ao GitHub Actions — o IP não é aceito."
  warn "Recrie a VM numa região brasileira antes de seguir."
  exit 1
fi
pause "Enter para continuar"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Instalar Python, Chrome e chromedriver na VM" 8
say "Instalando tudo o que a extração precisa (leva alguns minutos)..."
printf '\n'
remoto 'bash -s' <<'REMOTO'
set -e
export DEBIAN_FRONTEND=noninteractive
sudo apt-get update -qq
sudo apt-get install -y -qq python3 python3-pip python3-venv git curl unzip jq ca-certificates fonts-liberation

# Swap: o Chrome headless derruba VMs de 1-2 GB sem memória de folga.
if [ ! -f /swapfile ] && [ "$(free -m | awk '/Mem:/{print $2}')" -lt 4000 ]; then
  sudo fallocate -l 2G /swapfile
  sudo chmod 600 /swapfile
  sudo mkswap /swapfile >/dev/null
  sudo swapon /swapfile
  grep -q '^/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab >/dev/null
  echo "swap de 2 GB criado"
fi

# Google Chrome estável
if ! command -v google-chrome >/dev/null 2>&1; then
  curl -fsSL -o /tmp/chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  sudo apt-get install -y -qq /tmp/chrome.deb
  rm -f /tmp/chrome.deb
fi
CHROME_VER=$(google-chrome --version | awk '{print $3}')
CHROME_MAJOR=${CHROME_VER%%.*}
echo "Chrome instalado: $CHROME_VER"

# chromedriver da mesma major, via Chrome for Testing
NEED_DRIVER=1
if command -v chromedriver >/dev/null 2>&1; then
  DRIVER_MAJOR=$(chromedriver --version | awk '{print $2}' | cut -d. -f1)
  [ "$DRIVER_MAJOR" = "$CHROME_MAJOR" ] && NEED_DRIVER=0
fi
if [ "$NEED_DRIVER" = "1" ]; then
  JSON=https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json
  URL=$(curl -s "$JSON" | jq -r --arg m "$CHROME_MAJOR" '
    [.versions[] | select(.version | startswith($m + "."))] | last
    | .downloads.chromedriver[] | select(.platform=="linux64") | .url')
  if [ -z "$URL" ] || [ "$URL" = "null" ]; then
    URL=$(curl -s https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json \
      | jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform=="linux64") | .url')
  fi
  curl -fsSL -o /tmp/chromedriver.zip "$URL"
  unzip -o -q /tmp/chromedriver.zip -d /tmp
  sudo install -m 0755 /tmp/chromedriver-linux64/chromedriver /usr/bin/chromedriver
  rm -rf /tmp/chromedriver.zip /tmp/chromedriver-linux64
fi
echo "chromedriver instalado: $(chromedriver --version)"

# Fumaça: o Chrome headless abre uma página?
google-chrome --headless=new --no-sandbox --disable-gpu --dump-dom https://example.com >/dev/null 2>&1 \
  && echo "Chrome headless OK" || { echo "Chrome headless falhou"; exit 1; }
REMOTO
say "✓ Ambiente pronto na VM"
pause "Enter para continuar"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Registrar o runner do GitHub na VM" 6
say "Gerando um token de registro (válido por 1 hora) e instalando o runner"
say "como serviço, para subir sozinho a cada boot."
printf '\n'
REG_TOKEN=$(gh api -X POST "repos/${REPO}/actions/runners/registration-token" --jq .token)
if [[ -z "$REG_TOKEN" ]]; then
  warn "não consegui gerar o token — confira se o gh tem permissão de admin no repositório"
  exit 1
fi
remoto "REPO='${REPO}' REG_TOKEN='${REG_TOKEN}' RUNNER_NAME='${RUNNER_NAME}' RUNNER_LABEL='${RUNNER_LABEL}' bash -s" <<'REMOTO'
set -e
cd "$HOME"
if [ -d actions-runner ] && [ -f actions-runner/svc.sh ]; then
  echo "runner já existe; removendo o serviço antigo antes de reconfigurar"
  cd actions-runner
  sudo ./svc.sh stop  >/dev/null 2>&1 || true
  sudo ./svc.sh uninstall >/dev/null 2>&1 || true
  cd "$HOME"
else
  mkdir -p actions-runner
  cd actions-runner
  VER=$(curl -s https://api.github.com/repos/actions/runner/releases/latest | jq -r .tag_name | sed 's/^v//')
  curl -fsSL -o runner.tar.gz "https://github.com/actions/runner/releases/download/v${VER}/actions-runner-linux-x64-${VER}.tar.gz"
  tar xzf runner.tar.gz
  rm -f runner.tar.gz
  sudo ./bin/installdependencies.sh >/dev/null
  cd "$HOME"
fi
cd "$HOME/actions-runner"
./config.sh --unattended --replace \
  --url "https://github.com/${REPO}" \
  --token "$REG_TOKEN" \
  --name "$RUNNER_NAME" \
  --labels "$RUNNER_LABEL" \
  --work _work
sudo ./svc.sh install "$USER"
sudo ./svc.sh start
sleep 5
sudo ./svc.sh status | head -20
REMOTO
say "✓ Runner instalado como serviço"
pause "Enter para continuar"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Apontar o workflow para o runner" 2
say "Conferindo se o GitHub já enxerga o runner online..."
gh api "repos/${REPO}/actions/runners" \
  --jq '.runners[] | "  - \(.name): \(.status) [\(.labels | map(.name) | join(", "))]"' || true
printf '\n'
say "Agora a variável RUNNER_LABEL passa a direcionar o job de atualização."
set_var RUNNER_LABEL "$RUNNER_LABEL"
pause "Enter para continuar"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Validar rodando a atualização de ponta a ponta" 4
say "Disparando o workflow 'Atualizar Escala Diária HRO' no runner novo."
if confirm "Rodar agora? (ele atualiza o site com a escala de hoje)"; then
  gh workflow run daily-escala.yml --ref main
  sleep 8
  RUN_ID=$(gh run list --workflow daily-escala.yml --limit 1 --json databaseId --jq '.[0].databaseId')
  say "Acompanhando o run ${RUN_ID}..."
  gh run watch "$RUN_ID" --interval 15 || true
  gh run view "$RUN_ID" | head -25
else
  note "Você pode rodar depois: gh workflow run daily-escala.yml --ref main"
fi

finish
say "Manutenção do runner, quando precisar:"
note "  ssh ${VPS_USER}@${VPS_HOST}"
note "  cd ~/actions-runner && sudo ./svc.sh status   # ver o serviço"
note "  sudo ./svc.sh start | stop                    # controlar"
note "  journalctl -u actions.runner.* -n 100         # logs"
printf '\n'
note "Para voltar a rodar no runner do GitHub (vai falhar enquanto o bloqueio existir):"
note "  gh variable delete RUNNER_LABEL"
printf '\n'
